<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.29" />
    <PackageReference Include="StackExchange.Redis" Version="3.0.17" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NeuAI.Video.Application\NeuAI.Video.Application.csproj" />
    <ProjectReference Include="..\NeuAI.Video.Infrastructure\NeuAI.Video.Infrastructure.csproj" />
  </ItemGroup>
</Project>
